USE dbms_proj_demo;
GO

-- ---------- DOWN (drop FKs/PKs/tables if present) ----------
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_playername_teamid_team_id')
  ALTER TABLE PlayerName DROP CONSTRAINT fk_playername_teamid_team_id;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_playername_position_code')
  ALTER TABLE PlayerName DROP CONSTRAINT fk_playername_position_code;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_master_type_type')
  ALTER TABLE [master] DROP CONSTRAINT fk_master_type_type;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_master_playerid_id_')
  ALTER TABLE [master] DROP CONSTRAINT fk_master_playerid_id_;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_master_teamid_teamid')
  ALTER TABLE [master] DROP CONSTRAINT fk_master_teamid_teamid;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_playername_id')
  ALTER TABLE PlayerName DROP CONSTRAINT pk_playername_id;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_Type_Lookup_type_id')
  ALTER TABLE Type_Lookup DROP CONSTRAINT pk_Type_Lookup_type_id;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_clubid_teamid')
  ALTER TABLE ClubId DROP CONSTRAINT pk_clubid_teamid;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_position_code')
  ALTER TABLE Position DROP CONSTRAINT pk_position_code;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_master_sr_id')
  ALTER TABLE [master] DROP CONSTRAINT pk_master_sr_id;

DROP TABLE IF EXISTS Position;
-- (Intentionally not dropping master/ClubId/Type_Lookup/PlayerName – keep data)
GO

-- ---------- UP (metadata, PKs/FKs/checks) ----------
-- Create Position (if you don’t already have it)
IF OBJECT_ID('dbo.Position','U') IS NULL
BEGIN
  CREATE TABLE dbo.Position (
    Position VARCHAR(50) NULL,
    Code     VARCHAR(50) NOT NULL,
    CONSTRAINT pk_position_code PRIMARY KEY (Code)
  );
END

-- Normalize key columns on master
ALTER TABLE [master] ALTER COLUMN Sr      VARCHAR(50) NOT NULL;
ALTER TABLE [master] ALTER COLUMN Id      VARCHAR(50) NOT NULL;
-- These two are required helper keys (surrogates)
ALTER TABLE [master] ALTER COLUMN PlayerId_ INT NOT NULL;
ALTER TABLE [master] ALTER COLUMN TypeId    INT NOT NULL;

-- Primary keys
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_master_sr_id')
  ALTER TABLE [master] ADD CONSTRAINT pk_master_sr_id PRIMARY KEY (sr,id);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_clubid_teamid')
  ALTER TABLE [dbo].[ClubId] ADD CONSTRAINT pk_clubid_teamid PRIMARY KEY ([team id]);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='pk_Type_Lookup_type_id')
  ALTER TABLE [dbo].[Type_Lookup] ADD CONSTRAINT pk_Type_Lookup_type_id PRIMARY KEY (id);

-- Foreign keys from master
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_master_teamid_teamid')
  ALTER TABLE [master] ADD CONSTRAINT fk_master_teamid_teamid
  FOREIGN KEY (teamid) REFERENCES [ClubId]([team id]);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_master_playerid_id_')
  ALTER TABLE [master] ADD CONSTRAINT fk_master_playerid_id_
  FOREIGN KEY (playerid_) REFERENCES [PlayerName](id);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_master_type_type')
  ALTER TABLE [master] ADD CONSTRAINT fk_master_type_type
  FOREIGN KEY (typeid) REFERENCES [Type_Lookup](id);

-- PlayerName FKs
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_playername_position_code')
  ALTER TABLE PlayerName ADD CONSTRAINT fk_playername_position_code
  FOREIGN KEY (Position) REFERENCES Position(Code);

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='fk_playername_teamid_team_id')
  ALTER TABLE PlayerName ADD CONSTRAINT fk_playername_teamid_team_id
  FOREIGN KEY (teamId) REFERENCES ClubId([team ID]);

-- Core CHECK constraints on master
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_h_a')
  ALTER TABLE [master] ADD CONSTRAINT ck_master_h_a CHECK (h_a IN ('a','h'));
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_period')
  ALTER TABLE [master] ADD CONSTRAINT ck_master_period CHECK (period IN ('FirstHalf','PostGame','PreMatch','SecondHalf'));
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_outcomeType')
  ALTER TABLE [master] ADD CONSTRAINT ck_master_outcomeType CHECK (outcomeType IN ('Successful','Unsuccessful'));

-- (There are many 0/1 “flag” - running them fot strict validation)
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_isTouch')
  ALTER TABLE [master] ADD CONSTRAINT ck_master_isTouch CHECK (isTouch IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_isShot')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_isShot CHECK (isShot IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_isGoal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_isGoal CHECK (isGoal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_isOwnGoal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_isOwnGoal CHECK (isOwnGoal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotOpenPlay')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotOpenPlay CHECK (shotOpenPlay IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotCounter')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotCounter CHECK (shotCounter IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotSetPiece')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotSetPiece CHECK (shotSetPiece IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotOffTarget')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotOffTarget CHECK (shotOffTarget IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotOnPost')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotOnPost CHECK (shotOnPost IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotOnTarget')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotOnTarget CHECK (shotOnTarget IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotsTotal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotsTotal CHECK (shotsTotal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotBlocked')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotBlocked CHECK (shotBlocked IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotRightFoot')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotRightFoot CHECK (shotRightFoot IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotLeftFoot')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotLeftFoot CHECK (shotLeftFoot IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotHead')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotHead CHECK (shotHead IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shotObp')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shotObp CHECK (shotObp IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalOpenPlay')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalOpenPlay CHECK (goalOpenPlay IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalCounter')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalCounter CHECK (goalCounter IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalSetPiece')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalSetPiece CHECK (goalSetPiece IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_penaltyScored')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_penaltyScored CHECK (penaltyScored IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalOwn')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalOwn CHECK (goalOwn IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalNormal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalNormal CHECK (goalNormal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalRightFoot')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalRightFoot CHECK (goalRightFoot IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalLeftFoot')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalLeftFoot CHECK (goalLeftFoot IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_goalHead')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_goalHead CHECK (goalHead IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shortPassInaccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shortPassInaccurate CHECK (shortPassInaccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_shortPassAccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_shortPassAccurate CHECK (shortPassAccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassLong')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassLong CHECK (keyPassLong IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassShort')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassShort CHECK (keyPassShort IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassCross')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassCross CHECK (keyPassCross IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassCorner')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassCorner CHECK (keyPassCorner IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassThroughball')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassThroughball CHECK (keyPassThroughball IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassFreekick')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassFreekick CHECK (keyPassFreekick IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassThrowin')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassThrowin CHECK (keyPassThrowin IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keyPassOther')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keyPassOther CHECK (keyPassOther IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_assistCross')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_assistCross CHECK (assistCross IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_assistCorner')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_assistCorner CHECK (assistCorner IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_assistThroughball')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_assistThroughball CHECK (assistThroughball IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_assistFreekick')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_assistFreekick CHECK (assistFreekick IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_assistOther')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_assistOther CHECK (assistOther IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_dribbleLost')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_dribbleLost CHECK (dribbleLost IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_dribbleWon')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_dribbleWon CHECK (dribbleWon IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_challengeLost')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_challengeLost CHECK (challengeLost IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_interceptionWon')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_interceptionWon CHECK (interceptionWon IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_clearanceHead')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_clearanceHead CHECK (clearanceHead IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_foulGiven')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_foulGiven CHECK (foulGiven IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_foulCommitted')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_foulCommitted CHECK (foulCommitted IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_yellowCard')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_yellowCard CHECK (yellowCard IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_redCard')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_redCard CHECK (redCard IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_turnover')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_turnover CHECK (turnover IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_dispossessed')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_dispossessed CHECK (dispossessed IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_touches')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_touches CHECK (touches IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_assist')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_assist CHECK (assist IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_ballRecovery')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_ballRecovery CHECK (ballRecovery IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_clearanceEffective')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_clearanceEffective CHECK (clearanceEffective IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_clearanceTotal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_clearanceTotal CHECK (clearanceTotal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_clearanceOffTheLine')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_clearanceOffTheLine CHECK (clearanceOffTheLine IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_errorLeadsToGoal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_errorLeadsToGoal CHECK (errorLeadsToGoal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_errorLeadsToShot')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_errorLeadsToShot CHECK (errorLeadsToShot IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_interceptionAll')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_interceptionAll CHECK (interceptionAll IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keeperClaimHighWon')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keeperClaimHighWon CHECK (keeperClaimHighWon IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_parriedDanger')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_parriedDanger CHECK (parriedDanger IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_parriedSafe')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_parriedSafe CHECK (parriedSafe IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_collected')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_collected CHECK (collected IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keeperSaveInTheBox')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keeperSaveInTheBox CHECK (keeperSaveInTheBox IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keeperSaveTotal')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keeperSaveTotal CHECK (keeperSaveTotal IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keeperSmother')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keeperSmother CHECK (keeperSmother IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keeperSweeperLost')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keeperSweeperLost CHECK (keeperSweeperLost IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_keeperMissed')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_keeperMissed CHECK (keeperMissed IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passAccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passAccurate CHECK (passAccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passKey')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passKey CHECK (passKey IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passChipped')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passChipped CHECK (passChipped IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passCrossAccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passCrossAccurate CHECK (passCrossAccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passCrossInaccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passCrossInaccurate CHECK (passCrossInaccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passLongBallAccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passLongBallAccurate CHECK (passLongBallAccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passLongBallInaccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passLongBallInaccurate CHECK (passLongBallInaccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passThroughBallAccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passThroughBallAccurate CHECK (passThroughBallAccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_passThroughBallInaccurate')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_passThroughBallInaccurate CHECK (passThroughBallInaccurate IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_penaltyConceded')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_penaltyConceded CHECK (penaltyConceded IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_penaltyMissed')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_penaltyMissed CHECK (penaltyMissed IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_penaltyWon')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_penaltyWon CHECK (penaltyWon IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_tackleLastMan')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_tackleLastMan CHECK (tackleLastMan IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_tackleLost')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_tackleLost CHECK (tackleLost IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_tackleWon')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_tackleWon CHECK (tackleWon IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_duelAerialWon')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_duelAerialWon CHECK (duelAerialWon IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_duelAerialLost')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_duelAerialLost CHECK (duelAerialLost IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_offensiveDuel')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_offensiveDuel CHECK (offensiveDuel IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_defensiveDuel')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_defensiveDuel CHECK (defensiveDuel IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_bigChanceMissed')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_bigChanceMissed CHECK (bigChanceMissed IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_bigChanceScored')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_bigChanceScored CHECK (bigChanceScored IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_bigChanceCreated')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_bigChanceCreated CHECK (bigChanceCreated IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_overrun')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_overrun CHECK (overrun IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_successfulFinalThirdPasses')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_successfulFinalThirdPasses CHECK (successfulFinalThirdPasses IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_punches')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_punches CHECK (punches IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_throwIn')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_throwIn CHECK (throwIn IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_subOn')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_subOn CHECK (subOn IN ('0','1'));

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='ck_master_subOff')
    ALTER TABLE [master] ADD CONSTRAINT ck_master_subOff CHECK (subOff IN ('0','1'));
